spring.application.name=digital-library
spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=your_DB_URL
spring.datasource.username=your_DB_USERNAME
spring.datasource.password=your_DB_PASSWORD
spring.jpa.show.sql = true
book.max-allowed = 3
book.return.due-date=15
book.fine-per-day=1